name: check-links

on:
  workflow_dispatch: # allow manual trigger
  push:
    branches:
      - main
  schedule:
    # run every 24 hours at 12:00
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 12 * *'

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Read exclude_url_prefix
        id: read_prefix
        run: echo "::set-output name=prefix::$(paste -sd ',' exclude_url_prefix.txt)"
      - name: Read exclude_url_suffix
        id: read_suffix
        run: echo "::set-output name=suffix::$(paste -sd ',' exclude_url_suffix.txt)"

      - name: Run Broken Links Crawler (landing)
        uses: ScholliYT/Broken-Links-Crawler-Action@v3
        with:
          website_url: '${{ github.server_url }}/${{ github.repository }}'
          resolve_before_filtering: 'true'
          exclude_url_prefix: '${{ steps.read_prefix.outputs.prefix }}'
          exclude_url_suffix: '${{ steps.read_suffix.outputs.suffix }}'
          verbose: 'true'
          max_retry_time: 30
          max_retries: 5
          max_depth: 1
      - name: Run Broken Links Crawler (CCMv4-Metanotes.md)
        uses: ScholliYT/Broken-Links-Crawler-Action@v3
        with:
          website_url: '${{ github.server_url }}/${{ github.repository }}/blob/main/CCMv4-Metanotes.md'
          resolve_before_filtering: 'true'
          exclude_url_prefix: '${{ steps.read_prefix.outputs.prefix }}'
          exclude_url_suffix: '${{ steps.read_suffix.outputs.suffix }}'
          verbose: 'true'
          max_retry_time: 30
          max_retries: 5
          max_depth: 1
      - name: Run Broken Links Crawler (WISHLIST.md)
        uses: ScholliYT/Broken-Links-Crawler-Action@v3
        with:
          website_url: '${{ github.server_url }}/${{ github.repository }}/blob/main/WISHLIST.md'
          resolve_before_filtering: 'true'
          exclude_url_prefix: '${{ steps.read_prefix.outputs.prefix }}'
          exclude_url_suffix: '${{ steps.read_suffix.outputs.suffix }}'
          verbose: 'true'
          max_retry_time: 30
          max_retries: 5
          max_depth: 1
