name: check-links

on:
  workflow_dispatch: # allow manual trigger
  push:
    branches:
      - main
  schedule:
    # run every 6 hours
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */6 * * *'

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Run Broken Links Crawler
        uses: ScholliYT/Broken-Links-Crawler-Action@v3
        with:
          website_url: '${{ github.server_url }}/${{ github.repository }}'
          resolve_before_filtering: 'true'
          exclude_url_prefix: 'mailto:,https://www.linkedin.com,https://linkedin.com,https://github-cloud.s3.amazonaws.com,https://www.cyber.gov.au,https://cyber.gov.au'
          exclude_url_suffix: '.zip'
          exclude_url_contained: '/tree,/code_menu_contents,/hovercards/citation,/search/custom_scopes/'
          verbose: 'true'
          max_retry_time: 30
          max_retries: 5
          max_depth: 1
