name: check-links

on:
  workflow_dispatch: # allow manual trigger
  push:
    branches:
      - main
  schedule:
    # run every 24 hours at 12:00
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 12 * *'

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Load EXCLUDE_URL_PREFIX and EXCLUDE_URL_SUFFIX from files
        id: load_prefix_suffix
        run: |
          echo "EXCLUDE_URL_PREFIX=$(cat ./.github/data/exclude_url_prefix.txt | tr '\r\n' ',')" >> $GITHUB_ENV
          echo "EXCLUDE_URL_SUFFIX=$(cat ./.github/data/exclude_url_suffix.txt | tr '\r\n' ',')" >> $GITHUB_ENV
      - name: Run Broken Links Crawler (landing)
        uses: ScholliYT/Broken-Links-Crawler-Action@v3
        with:
          website_url: '${{ github.server_url }}/${{ github.repository }}'
          resolve_before_filtering: 'true'
          exclude_url_prefix: '${{ github.server_url }},${{ env.EXCLUDE_URL_PREFIX }}'
          exclude_url_suffix: '${{ env.EXCLUDE_URL_SUFFIX }}'
          verbose: 'true'
          max_retry_time: 30
          max_retries: 5
          max_depth: 1
          web_agent_string: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36'
      - name: Run Broken Links Crawler (CCMv4-Metanotes.md)
        uses: ScholliYT/Broken-Links-Crawler-Action@v3
        with:
          website_url: '${{ github.server_url }}/${{ github.repository }}/blob/main/CCMv4-Metanotes.md'
          resolve_before_filtering: 'true'
          exclude_url_prefix: '${{ github.server_url }},${{ env.EXCLUDE_URL_PREFIX }}'
          exclude_url_suffix: '${{ env.EXCLUDE_URL_SUFFIX }}'
          verbose: 'true'
          max_retry_time: 30
          max_retries: 5
          max_depth: 1
          web_agent_string: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36'
      - name: Run Broken Links Crawler (WISHLIST.md)
        uses: ScholliYT/Broken-Links-Crawler-Action@v3
        with:
          website_url: '${{ github.server_url }}/${{ github.repository }}/blob/main/WISHLIST.md'
          resolve_before_filtering: 'true'
          exclude_url_prefix: '${{ github.server_url }},${{ env.EXCLUDE_URL_PREFIX }}'
          exclude_url_suffix: '${{ env.EXCLUDE_URL_SUFFIX }}'
          verbose: 'true'
          max_retry_time: 30
          max_retries: 5
          max_depth: 1
          web_agent_string: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36'
