name: check-links

on:
  workflow_dispatch: # allow manual trigger
  push:
    branches:
      - main
  schedule:
    # run every 6 hours
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */12 * * *'

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Run Broken Links Crawler
        uses: ScholliYT/Broken-Links-Crawler-Action@v3
        with:
          website_url: '${{ github.server_url }}/${{ github.repository }}'
          resolve_before_filtering: 'true'
          exclude_url_prefix: 'mailto:,https://www.linkedin.com,https://linkedin.com,https://x.com,https://www.cyber.gov.au,https://cyber.gov.au,https://github-cloud.s3.amazonaws.com'
          exclude_url_suffix: '.zip'
          exclude_url_contained: '${{ github.repository }}/tree,${{ github.repository }}/code_menu_contents,${{ github.repository }}/hovercards/citation,${{ github.repository }}/search/custom_scopes/,${{ github.repository }}/commit/,${{ github.repository }}/pulls?q=,${{ github.repository }}/issues,${{ github.repository }}/runs,${{ github.repository }}/actions'
          verbose: 'true'
          web_agent_string: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36'
          connect_limit_per_host: 2
          max_retry_time: 30
          max_retries: 5
          max_depth: 2
